---
deployment:
  tasks:
    - export DEPLOYPATH=/home/caypfaseyfp1/public_html/
    - /bin/cp -R build/static $DEPLOYPATH
    - /bin/cp build/.htaccess $DEPLOYPATH
    - /bin/cp build/asset-manifest.json $DEPLOYPATH
    - /bin/cp build/favicon.ico $DEPLOYPATH
    - /bin/cp build/index.html $DEPLOYPATH
    - /bin/cp build/logo192.png $DEPLOYPATH
    - /bin/cp build/logo512.png $DEPLOYPATH
    - /bin/cp build/manifest.json $DEPLOYPATH
    - /bin/cp build/robots.txt $DEPLOYPATH